{{ if .Values.ui.ssl.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "fullname_letsencrypt" . }}-rolebinding
  labels:
    app: "{{ .Chart.Name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "fullname_letsencrypt" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "fullname_letsencrypt" . }}-sa
{{- end -}}
