{{ if .Values.ui.ssl.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fullname_letsencrypt" . }}-role
  labels:
    app: "{{ .Chart.Name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
rules:
  - apiGroups:      ['']
    resources:      ['secrets']
    verbs:          ["get", "watch", "list", "create", "update", "patch"]
{{- end }}
