# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#################################### REQUIRED CONFIGURATION ############################################################

define:
  - &HOSTNAME ""               # Host that would be vpn gateway
  - &COOKIE_SECRET ""          # OAuth proxy cookie session secret
  - &GITHUB_OAUTH_ID ""        # Github OAuth ID
  - &GITHUB_OAUTH_SECRET ""    # Github OAuth Secret
  - &GITHUB_ORG ""             # Github organization
  - &GITHUB_TEAM ""            # Github team
  - &DUO_IKEY ""               # DUO MFA IKey
  - &DUO_SKEY ""               # DUO MFA SKey
  - &DUO_HOST ""               # DUO MFA Host
  - &SSL_EMAIL ""              # Email that would be used to restore certificates and get notifications about expiration (https://letsencrypt.org/docs/expiration-emails/)
  - &SSL_ENABLED false         # Enable HTTPS
  - &SSL_PROD false            # If true let's encrypt will generate a production ready signed certificate.
           
                               ## WARNING: There are limits to request production ready certificates 
                               ##           (https://letsencrypt.org/docs/rate-limits/)
                               ##    Set to `false` during debuging, so that let's encrypt will generate untrusted certificates.


####################################### Developer configs ##############################################################

host: *HOSTNAME

ui:
  ssl:
    enabled: *SSL_ENABLED
    secret: openvpn-letsencrypt-secret
    prod: *SSL_PROD
    email: dev@grapevine.ai
  htmlConfigmap: default
  branding: "Grapevine AI OpenVPN"

duo:
  iKey: *DUO_IKEY
  sKey: *DUO_SKEY
  host: *DUO_HOST

persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
  size: 1Gi

easyrsa:
  vars:
    EASYRSA_REQ_COUNTRY: "US"
    EASYRSA_REQ_PROVINCE: "New York"
    EASYRSA_REQ_CITY: "New York"
    EASYRSA_REQ_ORG: "Grapevine AI"
    EASYRSA_REQ_EMAIL: "ncohen@grapevine.ai"
    EASYRSA_REQ_OU: "Dev Ops"
    EASYRSA_CA_EXPIRE: "3650"
    EASYRSA_CERT_EXPIRE: "30"
    EASYRSA_CRL_DAYS: "180"

debug: 0

openvpn:
  env:
    OVPN_RENEG_SEC: 0
  #push:
  #- "dhcp-option DOMAIN cloudposse.com"
  replicaCount: 1
  image:
    repository: cloudposse/openvpn
    tag: latest
    pullPolicy: Always
  service:
    name: openvpn
    type: LoadBalancer
    externalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

proxy:
  image:
    repository: nginx
    tag: alpine
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

ssl_terminator:
  replicaCount: 1
  image:
    repository: ployst/nginx-ssl-proxy
    tag: 0.0.7
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    http:
      name: http
      externalPort: 80
    https:
      name: https
      externalPort: 443
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

letsencrypt:
  replicaCount: 1
  image:
    repository: grapevineai/letsencrypt
    tag: latest
    pullPolicy: Always
  service:
    name: nginx
    type: ClusterIP
    externalPort: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

dashboard:
  image:
    repository: nginx
    tag: alpine
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

oauth:
  app:
    # Common oauth configs
    clientID: *GITHUB_OAUTH_ID
    clientSecret: *GITHUB_OAUTH_SECRET

    # Github specific configs
    githubOrg: *GITHUB_ORG
    githubTeam: *GITHUB_TEAM

    # Email filters
    emailDomains:
      - "*"
    emails:
    #      - admin@example.com

    skipAuthRegex:
    #  - ""

    # oAuth2 proxy configs
    requestLogging: false

    # oAuth2 proxy session cookie config
    cookieName:
    cookieSecret: *COOKIE_SECRET
    cookieDomain: *HOSTNAME
    cookieExpire:
    cookieRefresh:
    cookieHttponly: false

  image:
    repository: cloudposse/oauth2-proxy
    tag: latest
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
